# Identifying difficult to annotate tweets proof of concept

In [1]:
import pandas as pd

In the following dataset 20 contributors graded each tweet. 10 contributors graded the original sentiment evaluation.

In [2]:
df = pd.read_csv("weather-agg-DFE.csv")

Note the confidence score `what_emotion_does_the_author_express_specifically_about_the_weather:confidence` in the table below

In [3]:
df.head()

,_unit_id,_canary,_unit_state,_trusted_judgments,_last_judgment_at,what_emotion_does_the_author_express_specifically_about_the_weather,what_emotion_does_the_author_express_specifically_about_the_weather:confidence,gold_answer,tweet_id,tweet_text
0,314960380,NaN,finalized,20,8/24/13 0:21,Positive,0.8439,NaN,81990560,Grilling kabobs on the grill last night was am...
1,314960381,NaN,finalized,20,8/24/13 0:49,Negative,0.6963,NaN,84314377,The slowest day ever !! And the weather makes ...
2,314960382,NaN,finalized,20,8/24/13 0:55,Neutral / author is just sharing information,0.8802,NaN,82846118,Fire Weather Watch issued May 17 at 4:21PM CDT...
3,314960383,NaN,finalized,20,8/24/13 0:48,Positive,0.6897,NaN,82843785,Im going to lunch early today. The weather i...
4,314960384,NaN,finalized,20,8/24/13 1:19,Neutral / author is just sharing information,0.6153,NaN,82840144,Weekend Weather Causes Delays In I-270 Bridge ...

In [4]:
tweets = df[["what_emotion_does_the_author_express_specifically_about_the_weather:confidence","tweet_text"]]
tweets.columns= ['Confidence', 'text']
tweets

     Confidence                                               text
0        0.8439  Grilling kabobs on the grill last night was am...
1        0.6963  The slowest day ever !! And the weather makes ...
2        0.8802  Fire Weather Watch issued May 17 at 4:21PM CDT...
3        0.6897  Im going to lunch early today.   The weather i...
4        0.6153  Weekend Weather Causes Delays In I-270 Bridge ...
..          ...                                                ...
995      0.8747  good morning, it's sunny, pick up new car and ...
996      0.7509  Just saw Snow White working at Lady Foot Locke...
997      0.5128  RT @mention: Do NOT go out to move your car in...
998      0.7472  Not outside but looking out the window at them...
999      0.7345  RT @mention: Community Blood Center Media Bloo...

[1000 rows x 2 columns]

Observe that there are 745 tweets that have a confidence larger tha 0.5

In [5]:
len(tweets[tweets['Confidence'] > 0.5])

745

In [6]:
tweets['Confidence'] = tweets['Confidence'] > 0.5

/var/folders/v4/cft4t7hn0_g2knsl5cd3c33m0000gp/T/ipykernel_93745/3106272242.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets['Confidence'] = tweets['Confidence'] > 0.5

In [7]:
tweets

     Confidence                                               text
0          True  Grilling kabobs on the grill last night was am...
1          True  The slowest day ever !! And the weather makes ...
2          True  Fire Weather Watch issued May 17 at 4:21PM CDT...
3          True  Im going to lunch early today.   The weather i...
4          True  Weekend Weather Causes Delays In I-270 Bridge ...
..          ...                                                ...
995        True  good morning, it's sunny, pick up new car and ...
996        True  Just saw Snow White working at Lady Foot Locke...
997        True  RT @mention: Do NOT go out to move your car in...
998        True  Not outside but looking out the window at them...
999        True  RT @mention: Community Blood Center Media Bloo...

[1000 rows x 2 columns]

## Simple model to find difficult to annotate tweets

#### Word embedding using universal-sentence-encoder-large

In [8]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text
from sklearn.model_selection import train_test_split

In [9]:
module_url = "https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3"
embedding = hub.load(module_url)
print ("module %s loaded" % module_url)
def embed(input):
  return embedding(input)

2021-10-29 16:31:17.313433: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

module https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3 loaded

2021-10-29 16:31:21.639446: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(embed(tweets['text'].tolist()).numpy(), tweets['Confidence'], 
                                                    test_size=0.33, random_state=42)

In [11]:
# VOCAB_SIZE = 1000
# encoder = tf.keras.layers.TextVectorization(
#     max_tokens=VOCAB_SIZE)
# encoder.adapt(X_train)

In [12]:
# model = tf.keras.Sequential([
#     encoder,
#     tf.keras.layers.Embedding(
#         input_dim=len(encoder.get_vocabulary()),
#         output_dim=64,
#         # Use masking to handle the variable sequence lengths
#         mask_zero=True),
#     tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
#     tf.keras.layers.Dense(64, activation='relu'),
#     tf.keras.layers.Dense(1, activation='sigmoid')
# ])

In [13]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(32, activation='relu',),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [14]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [19]:
model.fit(X_train, y_train, epochs=500, batch_size=20, validation_split=0.2)

Epoch 1/500
27/27 [==============================] - 0s 3ms/step - loss: 0.0172 - accuracy: 0.9907 - val_loss: 2.2260 - val_accuracy: 0.6567
Epoch 2/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0131 - accuracy: 0.9944 - val_loss: 2.1376 - val_accuracy: 0.6567
Epoch 3/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0124 - accuracy: 0.9963 - val_loss: 2.3648 - val_accuracy: 0.6791
Epoch 4/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0164 - accuracy: 0.9963 - val_loss: 2.1484 - val_accuracy: 0.6418
Epoch 5/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0051 - accuracy: 0.9981 - val_loss: 2.2351 - val_accuracy: 0.6791
Epoch 6/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0191 - accuracy: 0.9907 - val_loss: 2.1425 - val_accuracy: 0.6418
Epoch 7/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0088 - accuracy: 0.9963 - val_loss: 2.2708 - val_accuracy: 0.6866
Epoch 8/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0143 - accuracy: 0.9963 - val_loss: 2.2352 - val_accuracy: 0.6642
Epoch 9/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0074 - accuracy: 0.9963 - val_loss: 2.2459 - val_accuracy: 0.6940
Epoch 10/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0072 - accuracy: 0.9981 - val_loss: 2.2690 - val_accuracy: 0.6493
Epoch 11/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0020 - accuracy: 1.0000 - val_loss: 2.3002 - val_accuracy: 0.6194
Epoch 12/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0023 - accuracy: 1.0000 - val_loss: 2.3056 - val_accuracy: 0.6493
Epoch 13/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0032 - accuracy: 0.9981 - val_loss: 2.2854 - val_accuracy: 0.6791
Epoch 14/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0046 - accuracy: 0.9981 - val_loss: 2.3319 - val_accuracy: 0.6493
Epoch 15/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0076 - accuracy: 0.9963 - val_loss: 2.4460 - val_accuracy: 0.6866
Epoch 16/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0107 - accuracy: 0.9963 - val_loss: 2.4726 - val_accuracy: 0.6866
Epoch 17/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0043 - accuracy: 0.9981 - val_loss: 2.4161 - val_accuracy: 0.7015
Epoch 18/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0031 - accuracy: 0.9981 - val_loss: 2.3953 - val_accuracy: 0.6493
Epoch 19/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0118 - accuracy: 0.9963 - val_loss: 2.4896 - val_accuracy: 0.6791
Epoch 20/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0025 - accuracy: 1.0000 - val_loss: 2.4974 - val_accuracy: 0.6418
Epoch 21/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0096 - accuracy: 0.9981 - val_loss: 2.5505 - val_accuracy: 0.6493
Epoch 22/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0013 - accuracy: 1.0000 - val_loss: 2.5274 - val_accuracy: 0.6194
Epoch 23/500
27/27 [==============================] - 0s 2ms/step - loss: 8.8387e-04 - accuracy: 1.0000 - val_loss: 2.5096 - val_accuracy: 0.6343
Epoch 24/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0034 - accuracy: 0.9981 - val_loss: 2.5690 - val_accuracy: 0.6343
Epoch 25/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0068 - accuracy: 0.9963 - val_loss: 2.6886 - val_accuracy: 0.6940
Epoch 26/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0048 - accuracy: 0.9981 - val_loss: 2.6586 - val_accuracy: 0.6119
Epoch 27/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0143 - accuracy: 0.9944 - val_loss: 2.5804 - val_accuracy: 0.6045
Epoch 28/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0108 - accuracy: 0.9963 - val_loss: 2.4083 - val_accuracy: 0.6642
Epoch 29/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 2.4261 - val_accuracy: 0.6567
Epoch 30/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0018 - accuracy: 1.0000 - val_loss: 2.4117 - val_accuracy: 0.6791
Epoch 31/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0092 - accuracy: 0.9981 - val_loss: 2.5002 - val_accuracy: 0.7015
Epoch 32/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0281 - accuracy: 0.9907 - val_loss: 2.4867 - val_accuracy: 0.6418
Epoch 33/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0047 - accuracy: 0.9981 - val_loss: 2.5424 - val_accuracy: 0.6269
Epoch 34/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 0.9981 - val_loss: 2.5177 - val_accuracy: 0.6493
Epoch 35/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0085 - accuracy: 0.9963 - val_loss: 2.4312 - val_accuracy: 0.6269
Epoch 36/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0102 - accuracy: 0.9944 - val_loss: 2.5780 - val_accuracy: 0.6194
Epoch 37/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0079 - accuracy: 0.9963 - val_loss: 2.5548 - val_accuracy: 0.5896
Epoch 38/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0021 - accuracy: 1.0000 - val_loss: 2.6051 - val_accuracy: 0.6418
Epoch 39/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0064 - accuracy: 0.9981 - val_loss: 2.6602 - val_accuracy: 0.6194
Epoch 40/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0116 - accuracy: 0.9963 - val_loss: 2.7402 - val_accuracy: 0.6119
Epoch 41/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0127 - accuracy: 0.9925 - val_loss: 2.6505 - val_accuracy: 0.6343
Epoch 42/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0086 - accuracy: 0.9963 - val_loss: 2.6612 - val_accuracy: 0.6343
Epoch 43/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0041 - accuracy: 0.9981 - val_loss: 2.6462 - val_accuracy: 0.6269
Epoch 44/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0013 - accuracy: 1.0000 - val_loss: 2.7230 - val_accuracy: 0.6567
Epoch 45/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0056 - accuracy: 0.9981 - val_loss: 2.7490 - val_accuracy: 0.6567
Epoch 46/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0038 - accuracy: 0.9981 - val_loss: 2.7001 - val_accuracy: 0.6493
Epoch 47/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0030 - accuracy: 0.9981 - val_loss: 2.6825 - val_accuracy: 0.6194
Epoch 48/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0029 - accuracy: 1.0000 - val_loss: 2.6813 - val_accuracy: 0.6642
Epoch 49/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0055 - accuracy: 0.9981 - val_loss: 2.7652 - val_accuracy: 0.6791
Epoch 50/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0013 - accuracy: 1.0000 - val_loss: 2.6721 - val_accuracy: 0.6567
Epoch 51/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0015 - accuracy: 1.0000 - val_loss: 2.7489 - val_accuracy: 0.6716
Epoch 52/500
27/27 [==============================] - 0s 2ms/step - loss: 8.4423e-04 - accuracy: 1.0000 - val_loss: 2.7786 - val_accuracy: 0.6642
Epoch 53/500
27/27 [==============================] - 0s 2ms/step - loss: 5.9111e-04 - accuracy: 1.0000 - val_loss: 2.7744 - val_accuracy: 0.6567
Epoch 54/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0041 - accuracy: 0.9981 - val_loss: 2.6520 - val_accuracy: 0.6343
Epoch 55/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0102 - accuracy: 0.9963 - val_loss: 2.7043 - val_accuracy: 0.6269
Epoch 56/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0119 - accuracy: 0.9963 - val_loss: 2.6658 - val_accuracy: 0.6642
Epoch 57/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0029 - accuracy: 1.0000 - val_loss: 2.6001 - val_accuracy: 0.6418
Epoch 58/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0026 - accuracy: 1.0000 - val_loss: 2.6592 - val_accuracy: 0.6493

Epoch 59/500
27/27 [==============================] - 0s 2ms/step - loss: 5.7342e-04 - accuracy: 1.0000 - val_loss: 2.6722 - val_accuracy: 0.6642
Epoch 60/500
27/27 [==============================] - 0s 2ms/step - loss: 4.6713e-04 - accuracy: 1.0000 - val_loss: 2.6832 - val_accuracy: 0.6716
Epoch 61/500
27/27 [==============================] - 0s 2ms/step - loss: 4.7342e-04 - accuracy: 1.0000 - val_loss: 2.7130 - val_accuracy: 0.6716
Epoch 62/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0017 - accuracy: 1.0000 - val_loss: 2.7764 - val_accuracy: 0.6866
Epoch 63/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0035 - accuracy: 0.9981 - val_loss: 2.7924 - val_accuracy: 0.6716
Epoch 64/500
27/27 [==============================] - 0s 2ms/step - loss: 8.4718e-04 - accuracy: 1.0000 - val_loss: 2.7935 - val_accuracy: 0.7015
Epoch 65/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0097 - accuracy: 0.9981 - val_loss: 2.7953 - val_accuracy: 0.6940
Epoch 66/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0070 - accuracy: 0.9963 - val_loss: 2.8652 - val_accuracy: 0.6716
Epoch 67/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0030 - accuracy: 0.9981 - val_loss: 2.7538 - val_accuracy: 0.6866
Epoch 68/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0032 - accuracy: 1.0000 - val_loss: 2.7531 - val_accuracy: 0.6716
Epoch 69/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0012 - accuracy: 1.0000 - val_loss: 2.8605 - val_accuracy: 0.6791
Epoch 70/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0036 - accuracy: 0.9981 - val_loss: 2.9946 - val_accuracy: 0.7015
Epoch 71/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0031 - accuracy: 0.9981 - val_loss: 2.9095 - val_accuracy: 0.6716
Epoch 72/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0013 - accuracy: 1.0000 - val_loss: 2.9432 - val_accuracy: 0.5896
Epoch 73/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0015 - accuracy: 1.0000 - val_loss: 2.9267 - val_accuracy: 0.6716
Epoch 74/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0100 - accuracy: 0.9981 - val_loss: 3.0088 - val_accuracy: 0.6045
Epoch 75/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0031 - accuracy: 0.9981 - val_loss: 3.2098 - val_accuracy: 0.6791
Epoch 76/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0036 - accuracy: 0.9981 - val_loss: 2.9433 - val_accuracy: 0.6343
Epoch 77/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0043 - accuracy: 0.9981 - val_loss: 2.9598 - val_accuracy: 0.6493
Epoch 78/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0084 - accuracy: 0.9981 - val_loss: 3.1203 - val_accuracy: 0.7239
Epoch 79/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0108 - accuracy: 0.9963 - val_loss: 2.9310 - val_accuracy: 0.6866
Epoch 80/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0154 - accuracy: 0.9944 - val_loss: 3.0968 - val_accuracy: 0.6119
Epoch 81/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0286 - accuracy: 0.9925 - val_loss: 2.8396 - val_accuracy: 0.6716
Epoch 82/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0166 - accuracy: 0.9944 - val_loss: 3.2819 - val_accuracy: 0.6418
Epoch 83/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0148 - accuracy: 0.9963 - val_loss: 3.1478 - val_accuracy: 0.6940
Epoch 84/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0374 - accuracy: 0.9869 - val_loss: 3.0105 - val_accuracy: 0.6940
Epoch 85/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0327 - accuracy: 0.9925 - val_loss: 2.8052 - val_accuracy: 0.6045
Epoch 86/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0140 - accuracy: 0.9981 - val_loss: 2.7357 - val_accuracy: 0.6343
Epoch 87/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0082 - accuracy: 0.9981 - val_loss: 2.8354 - val_accuracy: 0.6791
Epoch 88/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0050 - accuracy: 0.9981 - val_loss: 2.7028 - val_accuracy: 0.6418
Epoch 89/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0030 - accuracy: 0.9981 - val_loss: 2.6603 - val_accuracy: 0.6269
Epoch 90/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0027 - accuracy: 1.0000 - val_loss: 2.7172 - val_accuracy: 0.6493
Epoch 91/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0018 - accuracy: 0.9981 - val_loss: 2.7456 - val_accuracy: 0.6418
Epoch 92/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0061 - accuracy: 0.9963 - val_loss: 2.8853 - val_accuracy: 0.6940
Epoch 93/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0095 - accuracy: 0.9963 - val_loss: 2.9999 - val_accuracy: 0.5970
Epoch 94/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0254 - accuracy: 0.9944 - val_loss: 3.0079 - val_accuracy: 0.6642
Epoch 95/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0013 - accuracy: 1.0000 - val_loss: 2.7565 - val_accuracy: 0.6642
Epoch 96/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0013 - accuracy: 1.0000 - val_loss: 2.7580 - val_accuracy: 0.6493
Epoch 97/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0021 - accuracy: 1.0000 - val_loss: 2.7578 - val_accuracy: 0.6343
Epoch 98/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0015 - accuracy: 1.0000 - val_loss: 2.8376 - val_accuracy: 0.6791
Epoch 99/500
27/27 [==============================] - 0s 2ms/step - loss: 4.6912e-04 - accuracy: 1.0000 - val_loss: 2.8743 - val_accuracy: 0.6940
Epoch 100/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 0.9981 - val_loss: 2.9061 - val_accuracy: 0.6866
Epoch 101/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0054 - accuracy: 0.9981 - val_loss: 2.6885 - val_accuracy: 0.6567
Epoch 102/500
27/27 [==============================] - 0s 2ms/step - loss: 7.2726e-04 - accuracy: 1.0000 - val_loss: 2.7654 - val_accuracy: 0.6567
Epoch 103/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0018 - accuracy: 1.0000 - val_loss: 2.8468 - val_accuracy: 0.6642
Epoch 104/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0024 - accuracy: 1.0000 - val_loss: 2.9393 - val_accuracy: 0.6791
Epoch 105/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0013 - accuracy: 1.0000 - val_loss: 3.0316 - val_accuracy: 0.6940
Epoch 106/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0017 - accuracy: 1.0000 - val_loss: 3.0127 - val_accuracy: 0.6493
Epoch 107/500
27/27 [==============================] - 0s 2ms/step - loss: 5.1658e-04 - accuracy: 1.0000 - val_loss: 3.0152 - val_accuracy: 0.6269
Epoch 108/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0025 - accuracy: 1.0000 - val_loss: 3.1726 - val_accuracy: 0.6866
Epoch 109/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0069 - accuracy: 0.9963 - val_loss: 3.2132 - val_accuracy: 0.6567
Epoch 110/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0021 - accuracy: 1.0000 - val_loss: 3.1871 - val_accuracy: 0.6567
Epoch 111/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 3.2680 - val_accuracy: 0.6642
Epoch 112/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0018 - accuracy: 0.9981 - val_loss: 3.2541 - val_accuracy: 0.6493
Epoch 113/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0012 - accuracy: 1.0000 - val_loss: 3.2772 - val_accuracy: 0.6567
Epoch 114/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 3.4125 - val_accuracy: 0.6940
Epoch 115/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0065 - accuracy: 0.9963 - val_loss: 3.3861 - val_accuracy: 0.6194
Epoch 116/500

27/27 [==============================] - 0s 2ms/step - loss: 8.3618e-04 - accuracy: 1.0000 - val_loss: 3.4296 - val_accuracy: 0.6194
Epoch 117/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0020 - accuracy: 1.0000 - val_loss: 3.4389 - val_accuracy: 0.6567
Epoch 118/500
27/27 [==============================] - 0s 2ms/step - loss: 3.1187e-04 - accuracy: 1.0000 - val_loss: 3.4911 - val_accuracy: 0.6493
Epoch 119/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0021 - accuracy: 0.9981 - val_loss: 3.4079 - val_accuracy: 0.6343
Epoch 120/500
27/27 [==============================] - 0s 2ms/step - loss: 2.3536e-04 - accuracy: 1.0000 - val_loss: 3.4241 - val_accuracy: 0.6343
Epoch 121/500
27/27 [==============================] - 0s 2ms/step - loss: 2.1103e-04 - accuracy: 1.0000 - val_loss: 3.4461 - val_accuracy: 0.6418
Epoch 122/500
27/27 [==============================] - 0s 2ms/step - loss: 8.6672e-04 - accuracy: 1.0000 - val_loss: 3.5078 - val_accuracy: 0.6493
Epoch 123/500
27/27 [==============================] - 0s 2ms/step - loss: 3.6283e-04 - accuracy: 1.0000 - val_loss: 3.5209 - val_accuracy: 0.6418
Epoch 124/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0022 - accuracy: 0.9981 - val_loss: 3.5048 - val_accuracy: 0.6343
Epoch 125/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0017 - accuracy: 1.0000 - val_loss: 3.5878 - val_accuracy: 0.6716
Epoch 126/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0122 - accuracy: 0.9981 - val_loss: 3.5493 - val_accuracy: 0.6642
Epoch 127/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0043 - accuracy: 0.9981 - val_loss: 3.1771 - val_accuracy: 0.6418
Epoch 128/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0062 - accuracy: 0.9944 - val_loss: 3.1618 - val_accuracy: 0.6567
Epoch 129/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0046 - accuracy: 0.9963 - val_loss: 3.0381 - val_accuracy: 0.6642
Epoch 130/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0034 - accuracy: 1.0000 - val_loss: 3.0976 - val_accuracy: 0.6567
Epoch 131/500
27/27 [==============================] - 0s 2ms/step - loss: 9.7874e-04 - accuracy: 1.0000 - val_loss: 3.1381 - val_accuracy: 0.6343
Epoch 132/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0210 - accuracy: 0.9925 - val_loss: 3.1309 - val_accuracy: 0.6194
Epoch 133/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0058 - accuracy: 0.9981 - val_loss: 3.0344 - val_accuracy: 0.6418
Epoch 134/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0040 - accuracy: 0.9981 - val_loss: 3.0836 - val_accuracy: 0.6269
Epoch 135/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0052 - accuracy: 0.9963 - val_loss: 3.3710 - val_accuracy: 0.6567
Epoch 136/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0159 - accuracy: 0.9925 - val_loss: 3.0935 - val_accuracy: 0.6642
Epoch 137/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0079 - accuracy: 0.9963 - val_loss: 2.9865 - val_accuracy: 0.6716
Epoch 138/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0058 - accuracy: 0.9963 - val_loss: 3.0006 - val_accuracy: 0.6343
Epoch 139/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0089 - accuracy: 0.9981 - val_loss: 3.1018 - val_accuracy: 0.6493
Epoch 140/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0212 - accuracy: 0.9944 - val_loss: 2.9580 - val_accuracy: 0.7015
Epoch 141/500
27/27 [==============================] - 0s 2ms/step - loss: 5.1659e-04 - accuracy: 1.0000 - val_loss: 2.8191 - val_accuracy: 0.6791
Epoch 142/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0026 - accuracy: 1.0000 - val_loss: 2.9214 - val_accuracy: 0.6866
Epoch 143/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0041 - accuracy: 0.9981 - val_loss: 2.9360 - val_accuracy: 0.6866
Epoch 144/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 0.9981 - val_loss: 2.8978 - val_accuracy: 0.6343
Epoch 145/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0119 - accuracy: 0.9944 - val_loss: 2.9058 - val_accuracy: 0.7090
Epoch 146/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0156 - accuracy: 0.9944 - val_loss: 2.8962 - val_accuracy: 0.6642
Epoch 147/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0079 - accuracy: 0.9963 - val_loss: 2.9044 - val_accuracy: 0.6418
Epoch 148/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0026 - accuracy: 1.0000 - val_loss: 2.9455 - val_accuracy: 0.6493
Epoch 149/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0156 - accuracy: 0.9963 - val_loss: 2.9023 - val_accuracy: 0.6940
Epoch 150/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0020 - accuracy: 1.0000 - val_loss: 2.8258 - val_accuracy: 0.6866
Epoch 151/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0072 - accuracy: 0.9981 - val_loss: 2.7608 - val_accuracy: 0.6642
Epoch 152/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0073 - accuracy: 0.9963 - val_loss: 2.7594 - val_accuracy: 0.6940
Epoch 153/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0083 - accuracy: 0.9981 - val_loss: 2.6974 - val_accuracy: 0.6940
Epoch 154/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0020 - accuracy: 1.0000 - val_loss: 2.7333 - val_accuracy: 0.6866
Epoch 155/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0022 - accuracy: 1.0000 - val_loss: 2.7712 - val_accuracy: 0.6716
Epoch 156/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0155 - accuracy: 0.9981 - val_loss: 2.7542 - val_accuracy: 0.6866
Epoch 157/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0032 - accuracy: 0.9981 - val_loss: 2.7563 - val_accuracy: 0.7015
Epoch 158/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0142 - accuracy: 0.9963 - val_loss: 2.8633 - val_accuracy: 0.6642
Epoch 159/500
27/27 [==============================] - 0s 2ms/step - loss: 9.0623e-04 - accuracy: 1.0000 - val_loss: 2.9585 - val_accuracy: 0.6866
Epoch 160/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 2.9848 - val_accuracy: 0.6866
Epoch 161/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0022 - accuracy: 0.9981 - val_loss: 2.9634 - val_accuracy: 0.6940
Epoch 162/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0017 - accuracy: 1.0000 - val_loss: 3.0402 - val_accuracy: 0.6940
Epoch 163/500
27/27 [==============================] - 0s 2ms/step - loss: 9.5379e-04 - accuracy: 1.0000 - val_loss: 2.9522 - val_accuracy: 0.6866
Epoch 164/500
27/27 [==============================] - 0s 2ms/step - loss: 5.0801e-04 - accuracy: 1.0000 - val_loss: 2.9641 - val_accuracy: 0.6866
Epoch 165/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0028 - accuracy: 0.9981 - val_loss: 3.0155 - val_accuracy: 0.6940
Epoch 166/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0016 - accuracy: 1.0000 - val_loss: 3.0238 - val_accuracy: 0.6791
Epoch 167/500
27/27 [==============================] - 0s 2ms/step - loss: 2.2320e-04 - accuracy: 1.0000 - val_loss: 3.0430 - val_accuracy: 0.6791
Epoch 168/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0069 - accuracy: 0.9981 - val_loss: 3.3151 - val_accuracy: 0.6940
Epoch 169/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0068 - accuracy: 0.9981 - val_loss: 3.2408 - val_accuracy: 0.6418
Epoch 170/500
27/27 [==============================] - 0s 2ms/step - loss: 9.6309e-04 - accuracy: 1.0000 - val_loss: 3.3461 - val_accuracy: 0.6791
Epoch 171/500
27/27 [==============================] - 0s 2ms/step - loss: 9.5019e-04 - accuracy: 1.0000 - val_loss: 3.3699 - val_accuracy: 0.6791
Epoch 172/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0031 - accuracy: 0.9981 - val_loss: 3.2890 - val_accuracy: 0.6642

Epoch 173/500
27/27 [==============================] - 0s 2ms/step - loss: 7.7869e-04 - accuracy: 1.0000 - val_loss: 3.3001 - val_accuracy: 0.6716
Epoch 174/500
27/27 [==============================] - 0s 2ms/step - loss: 4.4869e-04 - accuracy: 1.0000 - val_loss: 3.3800 - val_accuracy: 0.6716
Epoch 175/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0020 - accuracy: 0.9981 - val_loss: 3.3026 - val_accuracy: 0.6642
Epoch 176/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0016 - accuracy: 1.0000 - val_loss: 3.4366 - val_accuracy: 0.6791
Epoch 177/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0017 - accuracy: 1.0000 - val_loss: 3.4623 - val_accuracy: 0.6642
Epoch 178/500
27/27 [==============================] - 0s 2ms/step - loss: 9.3034e-05 - accuracy: 1.0000 - val_loss: 3.4188 - val_accuracy: 0.6493
Epoch 179/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 3.3890 - val_accuracy: 0.6567
Epoch 180/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0010 - accuracy: 1.0000 - val_loss: 3.5386 - val_accuracy: 0.6716
Epoch 181/500
27/27 [==============================] - 0s 2ms/step - loss: 3.2953e-04 - accuracy: 1.0000 - val_loss: 3.6038 - val_accuracy: 0.6642
Epoch 182/500
27/27 [==============================] - 0s 2ms/step - loss: 5.9983e-04 - accuracy: 1.0000 - val_loss: 3.5373 - val_accuracy: 0.6642
Epoch 183/500
27/27 [==============================] - 0s 2ms/step - loss: 8.1025e-05 - accuracy: 1.0000 - val_loss: 3.5191 - val_accuracy: 0.6791
Epoch 184/500
27/27 [==============================] - 0s 2ms/step - loss: 2.2918e-04 - accuracy: 1.0000 - val_loss: 3.5094 - val_accuracy: 0.6791
Epoch 185/500
27/27 [==============================] - 0s 2ms/step - loss: 1.4625e-04 - accuracy: 1.0000 - val_loss: 3.5121 - val_accuracy: 0.6791
Epoch 186/500
27/27 [==============================] - 0s 2ms/step - loss: 1.2462e-04 - accuracy: 1.0000 - val_loss: 3.5250 - val_accuracy: 0.6791
Epoch 187/500
27/27 [==============================] - 0s 2ms/step - loss: 1.5243e-04 - accuracy: 1.0000 - val_loss: 3.5336 - val_accuracy: 0.6791
Epoch 188/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 3.5891 - val_accuracy: 0.6791
Epoch 189/500
27/27 [==============================] - 0s 2ms/step - loss: 2.8394e-04 - accuracy: 1.0000 - val_loss: 3.6590 - val_accuracy: 0.6642
Epoch 190/500
27/27 [==============================] - 0s 2ms/step - loss: 1.1395e-04 - accuracy: 1.0000 - val_loss: 3.6379 - val_accuracy: 0.6716
Epoch 191/500
27/27 [==============================] - 0s 2ms/step - loss: 1.5477e-04 - accuracy: 1.0000 - val_loss: 3.6311 - val_accuracy: 0.6716
Epoch 192/500
27/27 [==============================] - 0s 2ms/step - loss: 1.7948e-04 - accuracy: 1.0000 - val_loss: 3.6149 - val_accuracy: 0.6716
Epoch 193/500
27/27 [==============================] - 0s 2ms/step - loss: 8.1721e-05 - accuracy: 1.0000 - val_loss: 3.6151 - val_accuracy: 0.6791
Epoch 194/500
27/27 [==============================] - 0s 2ms/step - loss: 1.0094e-04 - accuracy: 1.0000 - val_loss: 3.6202 - val_accuracy: 0.6791
Epoch 195/500
27/27 [==============================] - 0s 2ms/step - loss: 9.9596e-05 - accuracy: 1.0000 - val_loss: 3.6304 - val_accuracy: 0.6791
Epoch 196/500
27/27 [==============================] - 0s 2ms/step - loss: 2.6643e-04 - accuracy: 1.0000 - val_loss: 3.6628 - val_accuracy: 0.6716
Epoch 197/500
27/27 [==============================] - 0s 2ms/step - loss: 8.1886e-04 - accuracy: 1.0000 - val_loss: 3.8121 - val_accuracy: 0.6642
Epoch 198/500
27/27 [==============================] - 0s 2ms/step - loss: 5.0551e-04 - accuracy: 1.0000 - val_loss: 3.7826 - val_accuracy: 0.6791
Epoch 199/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0046 - accuracy: 0.9963 - val_loss: 3.3881 - val_accuracy: 0.6418
Epoch 200/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0233 - accuracy: 0.9907 - val_loss: 3.1626 - val_accuracy: 0.6866
Epoch 201/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0182 - accuracy: 0.9944 - val_loss: 3.2291 - val_accuracy: 0.6567
Epoch 202/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0015 - accuracy: 1.0000 - val_loss: 3.4774 - val_accuracy: 0.6866
Epoch 203/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0114 - accuracy: 0.9963 - val_loss: 3.2687 - val_accuracy: 0.6493
Epoch 204/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0345 - accuracy: 0.9888 - val_loss: 2.9623 - val_accuracy: 0.6567
Epoch 205/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0396 - accuracy: 0.9888 - val_loss: 2.6030 - val_accuracy: 0.6269
Epoch 206/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0060 - accuracy: 0.9981 - val_loss: 2.6037 - val_accuracy: 0.6567
Epoch 207/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0124 - accuracy: 0.9963 - val_loss: 2.5901 - val_accuracy: 0.6418
Epoch 208/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0032 - accuracy: 0.9981 - val_loss: 2.6097 - val_accuracy: 0.6493
Epoch 209/500
27/27 [==============================] - 0s 2ms/step - loss: 6.3959e-04 - accuracy: 1.0000 - val_loss: 2.6265 - val_accuracy: 0.6418
Epoch 210/500
27/27 [==============================] - 0s 2ms/step - loss: 3.7947e-04 - accuracy: 1.0000 - val_loss: 2.6447 - val_accuracy: 0.6418
Epoch 211/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0088 - accuracy: 0.9963 - val_loss: 2.8462 - val_accuracy: 0.6418
Epoch 212/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0051 - accuracy: 0.9981 - val_loss: 2.8631 - val_accuracy: 0.6418
Epoch 213/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0041 - accuracy: 0.9981 - val_loss: 2.8586 - val_accuracy: 0.6418
Epoch 214/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0015 - accuracy: 1.0000 - val_loss: 2.8546 - val_accuracy: 0.6493
Epoch 215/500
27/27 [==============================] - 0s 2ms/step - loss: 9.3343e-04 - accuracy: 1.0000 - val_loss: 2.9246 - val_accuracy: 0.6493
Epoch 216/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0114 - accuracy: 0.9944 - val_loss: 3.2700 - val_accuracy: 0.6493
Epoch 217/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0115 - accuracy: 0.9963 - val_loss: 3.0453 - val_accuracy: 0.6269
Epoch 218/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0138 - accuracy: 0.9963 - val_loss: 3.1048 - val_accuracy: 0.6119
Epoch 219/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0070 - accuracy: 0.9981 - val_loss: 2.8874 - val_accuracy: 0.6194
Epoch 220/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0067 - accuracy: 0.9981 - val_loss: 2.8475 - val_accuracy: 0.6269
Epoch 221/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0055 - accuracy: 0.9963 - val_loss: 2.9029 - val_accuracy: 0.6866
Epoch 222/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0094 - accuracy: 0.9963 - val_loss: 2.6960 - val_accuracy: 0.6493
Epoch 223/500
27/27 [==============================] - 0s 2ms/step - loss: 5.3330e-04 - accuracy: 1.0000 - val_loss: 2.7605 - val_accuracy: 0.6493
Epoch 224/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0054 - accuracy: 0.9981 - val_loss: 2.8365 - val_accuracy: 0.6791
Epoch 225/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0019 - accuracy: 1.0000 - val_loss: 2.8157 - val_accuracy: 0.6791
Epoch 226/500
27/27 [==============================] - 0s 2ms/step - loss: 5.0782e-04 - accuracy: 1.0000 - val_loss: 2.8261 - val_accuracy: 0.6791
Epoch 227/500
27/27 [==============================] - 0s 2ms/step - loss: 9.0838e-04 - accuracy: 1.0000 - val_loss: 2.8062 - val_accuracy: 0.6642
Epoch 228/500
27/27 [==============================] - 0s 2ms/step - loss: 3.3552e-04 - accuracy: 1.0000 - val_loss: 2.8299 - val_accuracy: 0.6567
Epoch 229/500

27/27 [==============================] - 0s 2ms/step - loss: 3.1335e-04 - accuracy: 1.0000 - val_loss: 2.8593 - val_accuracy: 0.6716
Epoch 230/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 2.8972 - val_accuracy: 0.6716
Epoch 231/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0012 - accuracy: 1.0000 - val_loss: 2.8309 - val_accuracy: 0.6343
Epoch 232/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0013 - accuracy: 1.0000 - val_loss: 2.9604 - val_accuracy: 0.6567
Epoch 233/500
27/27 [==============================] - 0s 2ms/step - loss: 3.3435e-04 - accuracy: 1.0000 - val_loss: 3.0330 - val_accuracy: 0.6567
Epoch 234/500
27/27 [==============================] - 0s 2ms/step - loss: 3.1882e-04 - accuracy: 1.0000 - val_loss: 3.0599 - val_accuracy: 0.6567
Epoch 235/500
27/27 [==============================] - 0s 2ms/step - loss: 2.8627e-04 - accuracy: 1.0000 - val_loss: 3.0773 - val_accuracy: 0.6567
Epoch 236/500
27/27 [==============================] - 0s 2ms/step - loss: 7.1018e-04 - accuracy: 1.0000 - val_loss: 3.1040 - val_accuracy: 0.6493
Epoch 237/500
27/27 [==============================] - 0s 2ms/step - loss: 6.7645e-04 - accuracy: 1.0000 - val_loss: 3.1307 - val_accuracy: 0.6567
Epoch 238/500
27/27 [==============================] - 0s 2ms/step - loss: 2.8535e-04 - accuracy: 1.0000 - val_loss: 3.1483 - val_accuracy: 0.6567
Epoch 239/500
27/27 [==============================] - 0s 2ms/step - loss: 1.7580e-04 - accuracy: 1.0000 - val_loss: 3.1697 - val_accuracy: 0.6493
Epoch 240/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0018 - accuracy: 0.9981 - val_loss: 3.2407 - val_accuracy: 0.6716
Epoch 241/500
27/27 [==============================] - 0s 2ms/step - loss: 3.7654e-04 - accuracy: 1.0000 - val_loss: 3.2634 - val_accuracy: 0.6866
Epoch 242/500
27/27 [==============================] - 0s 2ms/step - loss: 7.2605e-04 - accuracy: 1.0000 - val_loss: 3.2420 - val_accuracy: 0.6716
Epoch 243/500
27/27 [==============================] - 0s 2ms/step - loss: 6.2969e-04 - accuracy: 1.0000 - val_loss: 3.2857 - val_accuracy: 0.6716
Epoch 244/500
27/27 [==============================] - 0s 2ms/step - loss: 2.2866e-04 - accuracy: 1.0000 - val_loss: 3.2917 - val_accuracy: 0.6642
Epoch 245/500
27/27 [==============================] - 0s 2ms/step - loss: 1.4329e-04 - accuracy: 1.0000 - val_loss: 3.2864 - val_accuracy: 0.6642
Epoch 246/500
27/27 [==============================] - 0s 2ms/step - loss: 1.2227e-04 - accuracy: 1.0000 - val_loss: 3.2892 - val_accuracy: 0.6642
Epoch 247/500
27/27 [==============================] - 0s 2ms/step - loss: 1.2763e-04 - accuracy: 1.0000 - val_loss: 3.2960 - val_accuracy: 0.6642
Epoch 248/500
27/27 [==============================] - 0s 2ms/step - loss: 1.6157e-04 - accuracy: 1.0000 - val_loss: 3.3127 - val_accuracy: 0.6642
Epoch 249/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0043 - accuracy: 0.9963 - val_loss: 3.2842 - val_accuracy: 0.6642
Epoch 250/500
27/27 [==============================] - 0s 2ms/step - loss: 9.7338e-04 - accuracy: 1.0000 - val_loss: 3.2888 - val_accuracy: 0.6567
Epoch 251/500
27/27 [==============================] - 0s 2ms/step - loss: 5.2279e-04 - accuracy: 1.0000 - val_loss: 3.4249 - val_accuracy: 0.6567
Epoch 252/500
27/27 [==============================] - 0s 2ms/step - loss: 5.0889e-04 - accuracy: 1.0000 - val_loss: 3.4012 - val_accuracy: 0.6493
Epoch 253/500
27/27 [==============================] - 0s 2ms/step - loss: 7.4554e-05 - accuracy: 1.0000 - val_loss: 3.3997 - val_accuracy: 0.6418
Epoch 254/500
27/27 [==============================] - 0s 2ms/step - loss: 1.3183e-04 - accuracy: 1.0000 - val_loss: 3.4087 - val_accuracy: 0.6418
Epoch 255/500
27/27 [==============================] - 0s 2ms/step - loss: 1.6201e-04 - accuracy: 1.0000 - val_loss: 3.4365 - val_accuracy: 0.6493
Epoch 256/500
27/27 [==============================] - 0s 2ms/step - loss: 9.5428e-04 - accuracy: 1.0000 - val_loss: 3.6125 - val_accuracy: 0.6791
Epoch 257/500
27/27 [==============================] - 0s 2ms/step - loss: 9.3320e-04 - accuracy: 1.0000 - val_loss: 3.6399 - val_accuracy: 0.6716
Epoch 258/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0012 - accuracy: 1.0000 - val_loss: 3.5607 - val_accuracy: 0.6642
Epoch 259/500
27/27 [==============================] - 0s 2ms/step - loss: 2.0127e-04 - accuracy: 1.0000 - val_loss: 3.5108 - val_accuracy: 0.6493
Epoch 260/500
27/27 [==============================] - 0s 2ms/step - loss: 5.9287e-05 - accuracy: 1.0000 - val_loss: 3.5374 - val_accuracy: 0.6493
Epoch 261/500
27/27 [==============================] - 0s 2ms/step - loss: 1.2110e-04 - accuracy: 1.0000 - val_loss: 3.5676 - val_accuracy: 0.6567
Epoch 262/500
27/27 [==============================] - 0s 2ms/step - loss: 1.0273e-04 - accuracy: 1.0000 - val_loss: 3.5828 - val_accuracy: 0.6567
Epoch 263/500
27/27 [==============================] - 0s 2ms/step - loss: 5.3150e-05 - accuracy: 1.0000 - val_loss: 3.5913 - val_accuracy: 0.6567
Epoch 264/500
27/27 [==============================] - 0s 2ms/step - loss: 5.4829e-04 - accuracy: 1.0000 - val_loss: 3.6106 - val_accuracy: 0.6642
Epoch 265/500
27/27 [==============================] - 0s 2ms/step - loss: 9.6952e-05 - accuracy: 1.0000 - val_loss: 3.7065 - val_accuracy: 0.6716
Epoch 266/500
27/27 [==============================] - 0s 2ms/step - loss: 4.7914e-04 - accuracy: 1.0000 - val_loss: 3.8008 - val_accuracy: 0.6716
Epoch 267/500
27/27 [==============================] - 0s 2ms/step - loss: 8.5109e-05 - accuracy: 1.0000 - val_loss: 3.8404 - val_accuracy: 0.6642
Epoch 268/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0068 - accuracy: 0.9963 - val_loss: 3.4661 - val_accuracy: 0.6791
Epoch 269/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0021 - accuracy: 0.9981 - val_loss: 3.2204 - val_accuracy: 0.6567
Epoch 270/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0014 - accuracy: 1.0000 - val_loss: 3.5366 - val_accuracy: 0.6716
Epoch 271/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 0.9981 - val_loss: 3.3297 - val_accuracy: 0.6269
Epoch 272/500
27/27 [==============================] - 0s 2ms/step - loss: 2.5977e-04 - accuracy: 1.0000 - val_loss: 3.3476 - val_accuracy: 0.6269
Epoch 273/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0101 - accuracy: 0.9981 - val_loss: 3.3886 - val_accuracy: 0.6642
Epoch 274/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0251 - accuracy: 0.9925 - val_loss: 3.1585 - val_accuracy: 0.6045
Epoch 275/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0310 - accuracy: 0.9888 - val_loss: 2.8642 - val_accuracy: 0.6567
Epoch 276/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0181 - accuracy: 0.9944 - val_loss: 2.7226 - val_accuracy: 0.6418
Epoch 277/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0091 - accuracy: 0.9963 - val_loss: 2.7403 - val_accuracy: 0.6940
Epoch 278/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0013 - accuracy: 1.0000 - val_loss: 2.7954 - val_accuracy: 0.7090
Epoch 279/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0014 - accuracy: 1.0000 - val_loss: 3.0449 - val_accuracy: 0.6866
Epoch 280/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 2.8636 - val_accuracy: 0.6866
Epoch 281/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0104 - accuracy: 0.9981 - val_loss: 2.8579 - val_accuracy: 0.6940
Epoch 282/500
27/27 [==============================] - 0s 2ms/step - loss: 4.1369e-04 - accuracy: 1.0000 - val_loss: 2.9029 - val_accuracy: 0.6866
Epoch 283/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0111 - accuracy: 0.9963 - val_loss: 2.8837 - val_accuracy: 0.7015
Epoch 284/500
27/27 [==============================] - 0s 2ms/step - loss: 9.3166e-04 - accuracy: 1.0000 - val_loss: 2.9263 - val_accuracy: 0.7090
Epoch 285/500

27/27 [==============================] - 0s 2ms/step - loss: 5.7427e-04 - accuracy: 1.0000 - val_loss: 2.8937 - val_accuracy: 0.6866
Epoch 286/500
27/27 [==============================] - 0s 2ms/step - loss: 2.8704e-04 - accuracy: 1.0000 - val_loss: 2.9033 - val_accuracy: 0.6716
Epoch 287/500
27/27 [==============================] - 0s 2ms/step - loss: 4.7220e-04 - accuracy: 1.0000 - val_loss: 2.9259 - val_accuracy: 0.6716
Epoch 288/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0035 - accuracy: 0.9981 - val_loss: 2.9909 - val_accuracy: 0.7164
Epoch 289/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0012 - accuracy: 1.0000 - val_loss: 2.9673 - val_accuracy: 0.6716
Epoch 290/500
27/27 [==============================] - 0s 2ms/step - loss: 7.2120e-04 - accuracy: 1.0000 - val_loss: 2.9893 - val_accuracy: 0.6716
Epoch 291/500
27/27 [==============================] - 0s 2ms/step - loss: 8.0774e-04 - accuracy: 1.0000 - val_loss: 2.9664 - val_accuracy: 0.6866
Epoch 292/500
27/27 [==============================] - 0s 2ms/step - loss: 5.1763e-04 - accuracy: 1.0000 - val_loss: 2.9946 - val_accuracy: 0.6791
Epoch 293/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 3.1841 - val_accuracy: 0.7015
Epoch 294/500
27/27 [==============================] - 0s 2ms/step - loss: 2.9075e-04 - accuracy: 1.0000 - val_loss: 3.1725 - val_accuracy: 0.6940
Epoch 295/500
27/27 [==============================] - 0s 2ms/step - loss: 3.4077e-04 - accuracy: 1.0000 - val_loss: 3.1487 - val_accuracy: 0.6940
Epoch 296/500
27/27 [==============================] - 0s 2ms/step - loss: 2.0148e-04 - accuracy: 1.0000 - val_loss: 3.1318 - val_accuracy: 0.6866
Epoch 297/500
27/27 [==============================] - 0s 2ms/step - loss: 1.2837e-04 - accuracy: 1.0000 - val_loss: 3.1375 - val_accuracy: 0.6866
Epoch 298/500
27/27 [==============================] - 0s 2ms/step - loss: 8.1377e-04 - accuracy: 1.0000 - val_loss: 3.2373 - val_accuracy: 0.7015
Epoch 299/500
27/27 [==============================] - 0s 2ms/step - loss: 2.7545e-04 - accuracy: 1.0000 - val_loss: 3.2374 - val_accuracy: 0.7015
Epoch 300/500
27/27 [==============================] - 0s 2ms/step - loss: 1.7876e-04 - accuracy: 1.0000 - val_loss: 3.2320 - val_accuracy: 0.6940
Epoch 301/500
27/27 [==============================] - 0s 2ms/step - loss: 5.8129e-05 - accuracy: 1.0000 - val_loss: 3.2377 - val_accuracy: 0.6940
Epoch 302/500
27/27 [==============================] - 0s 2ms/step - loss: 3.7407e-04 - accuracy: 1.0000 - val_loss: 3.2536 - val_accuracy: 0.6940
Epoch 303/500
27/27 [==============================] - 0s 3ms/step - loss: 0.0015 - accuracy: 0.9981 - val_loss: 3.2857 - val_accuracy: 0.7164
Epoch 304/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0066 - accuracy: 0.9963 - val_loss: 3.2994 - val_accuracy: 0.6940
Epoch 305/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0141 - accuracy: 0.9981 - val_loss: 3.2047 - val_accuracy: 0.6940
Epoch 306/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0018 - accuracy: 1.0000 - val_loss: 3.1074 - val_accuracy: 0.6940
Epoch 307/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0018 - accuracy: 0.9981 - val_loss: 3.2229 - val_accuracy: 0.7015
Epoch 308/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0100 - accuracy: 0.9963 - val_loss: 3.3296 - val_accuracy: 0.6194
Epoch 309/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0272 - accuracy: 0.9925 - val_loss: 3.1555 - val_accuracy: 0.6716
Epoch 310/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0022 - accuracy: 0.9981 - val_loss: 2.9478 - val_accuracy: 0.6343
Epoch 311/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0091 - accuracy: 0.9981 - val_loss: 3.0428 - val_accuracy: 0.6567
Epoch 312/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0020 - accuracy: 1.0000 - val_loss: 3.2217 - val_accuracy: 0.6567
Epoch 313/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0032 - accuracy: 0.9981 - val_loss: 3.2125 - val_accuracy: 0.6418
Epoch 314/500
27/27 [==============================] - 0s 2ms/step - loss: 8.0492e-04 - accuracy: 1.0000 - val_loss: 3.2166 - val_accuracy: 0.6567
Epoch 315/500
27/27 [==============================] - 0s 2ms/step - loss: 1.8341e-04 - accuracy: 1.0000 - val_loss: 3.2276 - val_accuracy: 0.6567
Epoch 316/500
27/27 [==============================] - 0s 2ms/step - loss: 6.9777e-04 - accuracy: 1.0000 - val_loss: 3.3086 - val_accuracy: 0.6791
Epoch 317/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0084 - accuracy: 0.9963 - val_loss: 3.1670 - val_accuracy: 0.6716
Epoch 318/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0044 - accuracy: 0.9981 - val_loss: 2.9830 - val_accuracy: 0.6343
Epoch 319/500
27/27 [==============================] - 0s 2ms/step - loss: 4.4681e-04 - accuracy: 1.0000 - val_loss: 3.0430 - val_accuracy: 0.6493
Epoch 320/500
27/27 [==============================] - 0s 2ms/step - loss: 3.4843e-04 - accuracy: 1.0000 - val_loss: 3.0720 - val_accuracy: 0.6716
Epoch 321/500
27/27 [==============================] - 0s 2ms/step - loss: 1.1453e-04 - accuracy: 1.0000 - val_loss: 3.0896 - val_accuracy: 0.6716
Epoch 322/500
27/27 [==============================] - 0s 2ms/step - loss: 2.0661e-04 - accuracy: 1.0000 - val_loss: 3.1152 - val_accuracy: 0.6716
Epoch 323/500
27/27 [==============================] - 0s 2ms/step - loss: 1.8765e-04 - accuracy: 1.0000 - val_loss: 3.1374 - val_accuracy: 0.6716
Epoch 324/500
27/27 [==============================] - 0s 2ms/step - loss: 1.1215e-04 - accuracy: 1.0000 - val_loss: 3.1554 - val_accuracy: 0.6716
Epoch 325/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0021 - accuracy: 0.9981 - val_loss: 3.2465 - val_accuracy: 0.7015
Epoch 326/500
27/27 [==============================] - 0s 2ms/step - loss: 8.6571e-04 - accuracy: 1.0000 - val_loss: 3.2229 - val_accuracy: 0.6866
Epoch 327/500
27/27 [==============================] - 0s 2ms/step - loss: 2.5043e-04 - accuracy: 1.0000 - val_loss: 3.2420 - val_accuracy: 0.6866
Epoch 328/500
27/27 [==============================] - 0s 2ms/step - loss: 3.8526e-04 - accuracy: 1.0000 - val_loss: 3.1582 - val_accuracy: 0.6791
Epoch 329/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0069 - accuracy: 0.9981 - val_loss: 3.1449 - val_accuracy: 0.7090
Epoch 330/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0017 - accuracy: 1.0000 - val_loss: 3.1908 - val_accuracy: 0.6866
Epoch 331/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0029 - accuracy: 0.9981 - val_loss: 3.4122 - val_accuracy: 0.6642
Epoch 332/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0028 - accuracy: 0.9981 - val_loss: 3.4352 - val_accuracy: 0.6866
Epoch 333/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0025 - accuracy: 0.9981 - val_loss: 3.5759 - val_accuracy: 0.6418
Epoch 334/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0046 - accuracy: 0.9981 - val_loss: 3.6579 - val_accuracy: 0.6791
Epoch 335/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0102 - accuracy: 0.9963 - val_loss: 3.5990 - val_accuracy: 0.6194
Epoch 336/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0083 - accuracy: 0.9944 - val_loss: 3.4304 - val_accuracy: 0.6418
Epoch 337/500
27/27 [==============================] - 0s 2ms/step - loss: 2.0738e-04 - accuracy: 1.0000 - val_loss: 3.4360 - val_accuracy: 0.6418
Epoch 338/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0024 - accuracy: 0.9981 - val_loss: 3.4113 - val_accuracy: 0.6493
Epoch 339/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0019 - accuracy: 0.9981 - val_loss: 3.6995 - val_accuracy: 0.6493
Epoch 340/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0112 - accuracy: 0.9963 - val_loss: 4.0361 - val_accuracy: 0.6418
Epoch 341/500

27/27 [==============================] - 0s 2ms/step - loss: 0.0051 - accuracy: 0.9981 - val_loss: 3.8360 - val_accuracy: 0.6493
Epoch 342/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0017 - accuracy: 1.0000 - val_loss: 3.7592 - val_accuracy: 0.6343
Epoch 343/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0207 - accuracy: 0.9944 - val_loss: 3.4199 - val_accuracy: 0.6716
Epoch 344/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0123 - accuracy: 0.9907 - val_loss: 3.2653 - val_accuracy: 0.7164
Epoch 345/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0439 - accuracy: 0.9944 - val_loss: 2.7982 - val_accuracy: 0.6567
Epoch 346/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0074 - accuracy: 0.9981 - val_loss: 2.8584 - val_accuracy: 0.6716
Epoch 347/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0225 - accuracy: 0.9925 - val_loss: 2.5526 - val_accuracy: 0.6567
Epoch 348/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0109 - accuracy: 0.9944 - val_loss: 2.4103 - val_accuracy: 0.6791
Epoch 349/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0051 - accuracy: 0.9981 - val_loss: 2.5271 - val_accuracy: 0.6791
Epoch 350/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0030 - accuracy: 0.9981 - val_loss: 2.5522 - val_accuracy: 0.6642
Epoch 351/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 2.6249 - val_accuracy: 0.6716
Epoch 352/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0032 - accuracy: 0.9981 - val_loss: 2.8084 - val_accuracy: 0.6791
Epoch 353/500
27/27 [==============================] - 0s 2ms/step - loss: 7.9049e-04 - accuracy: 1.0000 - val_loss: 2.9154 - val_accuracy: 0.6940
Epoch 354/500
27/27 [==============================] - 0s 2ms/step - loss: 7.1165e-04 - accuracy: 1.0000 - val_loss: 2.8962 - val_accuracy: 0.6791
Epoch 355/500
27/27 [==============================] - 0s 2ms/step - loss: 4.4385e-04 - accuracy: 1.0000 - val_loss: 2.9134 - val_accuracy: 0.6791
Epoch 356/500
27/27 [==============================] - 0s 2ms/step - loss: 2.8382e-04 - accuracy: 1.0000 - val_loss: 2.9168 - val_accuracy: 0.6791
Epoch 357/500
27/27 [==============================] - 0s 2ms/step - loss: 4.4326e-04 - accuracy: 1.0000 - val_loss: 2.9088 - val_accuracy: 0.6866
Epoch 358/500
27/27 [==============================] - 0s 2ms/step - loss: 3.0202e-04 - accuracy: 1.0000 - val_loss: 2.9214 - val_accuracy: 0.6940
Epoch 359/500
27/27 [==============================] - 0s 2ms/step - loss: 7.2405e-04 - accuracy: 1.0000 - val_loss: 3.0068 - val_accuracy: 0.6716
Epoch 360/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0010 - accuracy: 1.0000 - val_loss: 3.0312 - val_accuracy: 0.6716
Epoch 361/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0025 - accuracy: 0.9981 - val_loss: 2.8878 - val_accuracy: 0.6642
Epoch 362/500
27/27 [==============================] - 0s 2ms/step - loss: 6.6191e-04 - accuracy: 1.0000 - val_loss: 2.8936 - val_accuracy: 0.6418
Epoch 363/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0020 - accuracy: 1.0000 - val_loss: 3.0237 - val_accuracy: 0.6866
Epoch 364/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0017 - accuracy: 1.0000 - val_loss: 3.1324 - val_accuracy: 0.7090
Epoch 365/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0025 - accuracy: 0.9981 - val_loss: 3.1695 - val_accuracy: 0.6791
Epoch 366/500
27/27 [==============================] - 0s 2ms/step - loss: 1.5010e-04 - accuracy: 1.0000 - val_loss: 3.1482 - val_accuracy: 0.6791
Epoch 367/500
27/27 [==============================] - 0s 2ms/step - loss: 3.1468e-04 - accuracy: 1.0000 - val_loss: 3.1817 - val_accuracy: 0.6716
Epoch 368/500
27/27 [==============================] - 0s 2ms/step - loss: 2.4017e-04 - accuracy: 1.0000 - val_loss: 3.2049 - val_accuracy: 0.6716
Epoch 369/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0010 - accuracy: 1.0000 - val_loss: 3.3062 - val_accuracy: 0.6866
Epoch 370/500
27/27 [==============================] - 0s 2ms/step - loss: 8.3126e-04 - accuracy: 1.0000 - val_loss: 3.3310 - val_accuracy: 0.6866
Epoch 371/500
27/27 [==============================] - 0s 2ms/step - loss: 1.2491e-04 - accuracy: 1.0000 - val_loss: 3.3431 - val_accuracy: 0.6866
Epoch 372/500
27/27 [==============================] - 0s 2ms/step - loss: 1.7039e-04 - accuracy: 1.0000 - val_loss: 3.3575 - val_accuracy: 0.6866
Epoch 373/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0010 - accuracy: 1.0000 - val_loss: 3.3661 - val_accuracy: 0.6418
Epoch 374/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0107 - accuracy: 0.9963 - val_loss: 3.3609 - val_accuracy: 0.6791
Epoch 375/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0045 - accuracy: 0.9981 - val_loss: 3.2995 - val_accuracy: 0.6567
Epoch 376/500
27/27 [==============================] - 0s 2ms/step - loss: 5.1499e-04 - accuracy: 1.0000 - val_loss: 3.3625 - val_accuracy: 0.6642
Epoch 377/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0107 - accuracy: 0.9981 - val_loss: 3.3611 - val_accuracy: 0.6791
Epoch 378/500
27/27 [==============================] - 0s 2ms/step - loss: 4.0919e-04 - accuracy: 1.0000 - val_loss: 3.3454 - val_accuracy: 0.6940
Epoch 379/500
27/27 [==============================] - 0s 2ms/step - loss: 4.1688e-04 - accuracy: 1.0000 - val_loss: 3.3476 - val_accuracy: 0.6866
Epoch 380/500
27/27 [==============================] - 0s 2ms/step - loss: 3.5532e-04 - accuracy: 1.0000 - val_loss: 3.3577 - val_accuracy: 0.6791
Epoch 381/500
27/27 [==============================] - 0s 2ms/step - loss: 5.6607e-04 - accuracy: 1.0000 - val_loss: 3.3507 - val_accuracy: 0.6716
Epoch 382/500
27/27 [==============================] - 0s 2ms/step - loss: 2.5885e-04 - accuracy: 1.0000 - val_loss: 3.3824 - val_accuracy: 0.6716
Epoch 383/500
27/27 [==============================] - 0s 2ms/step - loss: 2.8051e-04 - accuracy: 1.0000 - val_loss: 3.3911 - val_accuracy: 0.6716
Epoch 384/500
27/27 [==============================] - 0s 2ms/step - loss: 4.2696e-04 - accuracy: 1.0000 - val_loss: 3.4215 - val_accuracy: 0.6716
Epoch 385/500
27/27 [==============================] - 0s 2ms/step - loss: 3.7507e-04 - accuracy: 1.0000 - val_loss: 3.4340 - val_accuracy: 0.6716
Epoch 386/500
27/27 [==============================] - 0s 2ms/step - loss: 8.7872e-05 - accuracy: 1.0000 - val_loss: 3.4567 - val_accuracy: 0.6716
Epoch 387/500
27/27 [==============================] - 0s 2ms/step - loss: 1.2691e-04 - accuracy: 1.0000 - val_loss: 3.4679 - val_accuracy: 0.6716
Epoch 388/500
27/27 [==============================] - 0s 2ms/step - loss: 1.8076e-04 - accuracy: 1.0000 - val_loss: 3.4836 - val_accuracy: 0.6716
Epoch 389/500
27/27 [==============================] - 0s 2ms/step - loss: 6.6927e-04 - accuracy: 1.0000 - val_loss: 3.4177 - val_accuracy: 0.6493
Epoch 390/500
27/27 [==============================] - 0s 2ms/step - loss: 3.8915e-04 - accuracy: 1.0000 - val_loss: 3.4545 - val_accuracy: 0.6567
Epoch 391/500
27/27 [==============================] - 0s 2ms/step - loss: 5.2969e-04 - accuracy: 1.0000 - val_loss: 3.5159 - val_accuracy: 0.6642
Epoch 392/500
27/27 [==============================] - 0s 2ms/step - loss: 2.1036e-04 - accuracy: 1.0000 - val_loss: 3.5669 - val_accuracy: 0.6642
Epoch 393/500
27/27 [==============================] - 0s 2ms/step - loss: 4.2106e-04 - accuracy: 1.0000 - val_loss: 3.5935 - val_accuracy: 0.6567
Epoch 394/500
27/27 [==============================] - 0s 2ms/step - loss: 6.1442e-04 - accuracy: 1.0000 - val_loss: 3.6267 - val_accuracy: 0.6493
Epoch 395/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0015 - accuracy: 0.9981 - val_loss: 3.6557 - val_accuracy: 0.6866
Epoch 396/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0136 - accuracy: 0.9944 - val_loss: 3.3832 - val_accuracy: 0.6493
Epoch 397/500

27/27 [==============================] - 0s 2ms/step - loss: 0.0020 - accuracy: 1.0000 - val_loss: 3.5587 - val_accuracy: 0.7090
Epoch 398/500
27/27 [==============================] - 0s 2ms/step - loss: 6.3613e-04 - accuracy: 1.0000 - val_loss: 3.5628 - val_accuracy: 0.7015
Epoch 399/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 3.5170 - val_accuracy: 0.6716
Epoch 400/500
27/27 [==============================] - 0s 2ms/step - loss: 1.1294e-04 - accuracy: 1.0000 - val_loss: 3.5170 - val_accuracy: 0.6642
Epoch 401/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0053 - accuracy: 0.9981 - val_loss: 3.6627 - val_accuracy: 0.7164
Epoch 402/500
27/27 [==============================] - 0s 2ms/step - loss: 5.5336e-04 - accuracy: 1.0000 - val_loss: 3.6564 - val_accuracy: 0.7090
Epoch 403/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0050 - accuracy: 0.9963 - val_loss: 3.5534 - val_accuracy: 0.6716
Epoch 404/500
27/27 [==============================] - 0s 2ms/step - loss: 2.6024e-04 - accuracy: 1.0000 - val_loss: 3.6707 - val_accuracy: 0.6642
Epoch 405/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0012 - accuracy: 1.0000 - val_loss: 3.6068 - val_accuracy: 0.6716
Epoch 406/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0176 - accuracy: 0.9944 - val_loss: 3.6755 - val_accuracy: 0.7015
Epoch 407/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0267 - accuracy: 0.9944 - val_loss: 3.2123 - val_accuracy: 0.6716
Epoch 408/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0019 - accuracy: 0.9981 - val_loss: 3.0358 - val_accuracy: 0.6493
Epoch 409/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0265 - accuracy: 0.9963 - val_loss: 3.0189 - val_accuracy: 0.6940
Epoch 410/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0067 - accuracy: 0.9963 - val_loss: 2.8927 - val_accuracy: 0.6866
Epoch 411/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0045 - accuracy: 0.9981 - val_loss: 2.9387 - val_accuracy: 0.6716
Epoch 412/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0033 - accuracy: 0.9981 - val_loss: 2.9929 - val_accuracy: 0.7015
Epoch 413/500
27/27 [==============================] - 0s 2ms/step - loss: 4.1547e-04 - accuracy: 1.0000 - val_loss: 3.0032 - val_accuracy: 0.6567
Epoch 414/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0028 - accuracy: 1.0000 - val_loss: 3.0666 - val_accuracy: 0.6940
Epoch 415/500
27/27 [==============================] - 0s 2ms/step - loss: 2.9213e-04 - accuracy: 1.0000 - val_loss: 3.2533 - val_accuracy: 0.6940
Epoch 416/500
27/27 [==============================] - 0s 2ms/step - loss: 9.5769e-04 - accuracy: 1.0000 - val_loss: 3.2711 - val_accuracy: 0.6940
Epoch 417/500
27/27 [==============================] - 0s 2ms/step - loss: 1.8717e-04 - accuracy: 1.0000 - val_loss: 3.2870 - val_accuracy: 0.6940
Epoch 418/500
27/27 [==============================] - 0s 2ms/step - loss: 6.7803e-04 - accuracy: 1.0000 - val_loss: 3.3194 - val_accuracy: 0.6940
Epoch 419/500
27/27 [==============================] - 0s 2ms/step - loss: 2.4509e-04 - accuracy: 1.0000 - val_loss: 3.3542 - val_accuracy: 0.6940
Epoch 420/500
27/27 [==============================] - 0s 2ms/step - loss: 3.9415e-04 - accuracy: 1.0000 - val_loss: 3.3569 - val_accuracy: 0.6940
Epoch 421/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0026 - accuracy: 0.9981 - val_loss: 3.5420 - val_accuracy: 0.6940
Epoch 422/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0037 - accuracy: 0.9981 - val_loss: 3.6626 - val_accuracy: 0.6866
Epoch 423/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0077 - accuracy: 0.9981 - val_loss: 3.5667 - val_accuracy: 0.6791
Epoch 424/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0051 - accuracy: 0.9981 - val_loss: 3.0338 - val_accuracy: 0.6716
Epoch 425/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0053 - accuracy: 0.9944 - val_loss: 3.0332 - val_accuracy: 0.6716
Epoch 426/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0119 - accuracy: 0.9944 - val_loss: 3.2745 - val_accuracy: 0.6940
Epoch 427/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0038 - accuracy: 1.0000 - val_loss: 3.3614 - val_accuracy: 0.6716
Epoch 428/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0018 - accuracy: 0.9981 - val_loss: 3.2735 - val_accuracy: 0.6716
Epoch 429/500
27/27 [==============================] - 0s 2ms/step - loss: 8.3135e-04 - accuracy: 1.0000 - val_loss: 3.2743 - val_accuracy: 0.6642
Epoch 430/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0031 - accuracy: 0.9981 - val_loss: 3.3277 - val_accuracy: 0.6791
Epoch 431/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0074 - accuracy: 0.9981 - val_loss: 3.0862 - val_accuracy: 0.6493
Epoch 432/500
27/27 [==============================] - 0s 2ms/step - loss: 2.5890e-04 - accuracy: 1.0000 - val_loss: 3.2195 - val_accuracy: 0.6791
Epoch 433/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0146 - accuracy: 0.9944 - val_loss: 3.0240 - val_accuracy: 0.6940
Epoch 434/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0032 - accuracy: 0.9981 - val_loss: 3.0899 - val_accuracy: 0.6269
Epoch 435/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0021 - accuracy: 1.0000 - val_loss: 3.1636 - val_accuracy: 0.6642
Epoch 436/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0048 - accuracy: 0.9963 - val_loss: 3.2722 - val_accuracy: 0.6791
Epoch 437/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0085 - accuracy: 0.9981 - val_loss: 3.2999 - val_accuracy: 0.6418
Epoch 438/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0021 - accuracy: 0.9981 - val_loss: 3.2952 - val_accuracy: 0.6343
Epoch 439/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0032 - accuracy: 0.9981 - val_loss: 3.3189 - val_accuracy: 0.6716
Epoch 440/500
27/27 [==============================] - 0s 2ms/step - loss: 8.4908e-04 - accuracy: 1.0000 - val_loss: 3.4094 - val_accuracy: 0.6716
Epoch 441/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0029 - accuracy: 1.0000 - val_loss: 3.4784 - val_accuracy: 0.6716
Epoch 442/500
27/27 [==============================] - 0s 2ms/step - loss: 3.0821e-04 - accuracy: 1.0000 - val_loss: 3.4705 - val_accuracy: 0.6791
Epoch 443/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0017 - accuracy: 0.9981 - val_loss: 3.5861 - val_accuracy: 0.6493
Epoch 444/500
27/27 [==============================] - 0s 2ms/step - loss: 2.8372e-04 - accuracy: 1.0000 - val_loss: 3.6145 - val_accuracy: 0.6493
Epoch 445/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0128 - accuracy: 0.9981 - val_loss: 3.5561 - val_accuracy: 0.6642
Epoch 446/500
27/27 [==============================] - 0s 2ms/step - loss: 6.7461e-04 - accuracy: 1.0000 - val_loss: 3.5480 - val_accuracy: 0.6642
Epoch 447/500
27/27 [==============================] - 0s 2ms/step - loss: 3.8992e-04 - accuracy: 1.0000 - val_loss: 3.5323 - val_accuracy: 0.6567
Epoch 448/500
27/27 [==============================] - 0s 2ms/step - loss: 2.4621e-04 - accuracy: 1.0000 - val_loss: 3.5586 - val_accuracy: 0.6567
Epoch 449/500
27/27 [==============================] - 0s 2ms/step - loss: 1.6507e-04 - accuracy: 1.0000 - val_loss: 3.5653 - val_accuracy: 0.6493
Epoch 450/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0051 - accuracy: 0.9981 - val_loss: 3.8233 - val_accuracy: 0.6866
Epoch 451/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0021 - accuracy: 1.0000 - val_loss: 3.7623 - val_accuracy: 0.6642
Epoch 452/500
27/27 [==============================] - 0s 2ms/step - loss: 1.8414e-04 - accuracy: 1.0000 - val_loss: 3.7654 - val_accuracy: 0.6642
Epoch 453/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0143 - accuracy: 0.9963 - val_loss: 3.6747 - val_accuracy: 0.6493

Epoch 454/500
27/27 [==============================] - 0s 2ms/step - loss: 6.3846e-04 - accuracy: 1.0000 - val_loss: 3.5654 - val_accuracy: 0.6418
Epoch 455/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0064 - accuracy: 0.9981 - val_loss: 3.5777 - val_accuracy: 0.6642
Epoch 456/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0094 - accuracy: 0.9981 - val_loss: 3.2784 - val_accuracy: 0.6343
Epoch 457/500
27/27 [==============================] - 0s 2ms/step - loss: 2.7471e-04 - accuracy: 1.0000 - val_loss: 3.2464 - val_accuracy: 0.6269
Epoch 458/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0052 - accuracy: 0.9963 - val_loss: 3.4423 - val_accuracy: 0.7239
Epoch 459/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0032 - accuracy: 0.9981 - val_loss: 3.1959 - val_accuracy: 0.6642
Epoch 460/500
27/27 [==============================] - 0s 2ms/step - loss: 1.9301e-04 - accuracy: 1.0000 - val_loss: 3.2029 - val_accuracy: 0.6642
Epoch 461/500
27/27 [==============================] - 0s 2ms/step - loss: 1.9277e-04 - accuracy: 1.0000 - val_loss: 3.2222 - val_accuracy: 0.6642
Epoch 462/500
27/27 [==============================] - 0s 2ms/step - loss: 3.2077e-04 - accuracy: 1.0000 - val_loss: 3.2699 - val_accuracy: 0.6642
Epoch 463/500
27/27 [==============================] - 0s 2ms/step - loss: 1.5688e-04 - accuracy: 1.0000 - val_loss: 3.2849 - val_accuracy: 0.6642
Epoch 464/500
27/27 [==============================] - 0s 2ms/step - loss: 2.0353e-04 - accuracy: 1.0000 - val_loss: 3.2961 - val_accuracy: 0.6642
Epoch 465/500
27/27 [==============================] - 0s 2ms/step - loss: 5.4645e-04 - accuracy: 1.0000 - val_loss: 3.3706 - val_accuracy: 0.6716
Epoch 466/500
27/27 [==============================] - 0s 2ms/step - loss: 1.6950e-04 - accuracy: 1.0000 - val_loss: 3.3782 - val_accuracy: 0.6642
Epoch 467/500
27/27 [==============================] - 0s 2ms/step - loss: 7.2538e-04 - accuracy: 1.0000 - val_loss: 3.4442 - val_accuracy: 0.6791
Epoch 468/500
27/27 [==============================] - 0s 2ms/step - loss: 3.1614e-04 - accuracy: 1.0000 - val_loss: 3.4901 - val_accuracy: 0.6866
Epoch 469/500
27/27 [==============================] - 0s 2ms/step - loss: 1.9463e-04 - accuracy: 1.0000 - val_loss: 3.4907 - val_accuracy: 0.6791
Epoch 470/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0012 - accuracy: 1.0000 - val_loss: 3.7286 - val_accuracy: 0.7015
Epoch 471/500
27/27 [==============================] - 0s 2ms/step - loss: 1.4735e-04 - accuracy: 1.0000 - val_loss: 3.7108 - val_accuracy: 0.6791
Epoch 472/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0023 - accuracy: 0.9981 - val_loss: 3.7299 - val_accuracy: 0.6791
Epoch 473/500
27/27 [==============================] - 0s 2ms/step - loss: 2.6296e-04 - accuracy: 1.0000 - val_loss: 3.8613 - val_accuracy: 0.6866
Epoch 474/500
27/27 [==============================] - 0s 2ms/step - loss: 2.6314e-04 - accuracy: 1.0000 - val_loss: 3.8462 - val_accuracy: 0.6866
Epoch 475/500
27/27 [==============================] - 0s 2ms/step - loss: 1.8646e-04 - accuracy: 1.0000 - val_loss: 3.8203 - val_accuracy: 0.6866
Epoch 476/500
27/27 [==============================] - 0s 2ms/step - loss: 6.4998e-04 - accuracy: 1.0000 - val_loss: 3.7559 - val_accuracy: 0.6866
Epoch 477/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0072 - accuracy: 0.9981 - val_loss: 3.8611 - val_accuracy: 0.6940
Epoch 478/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0044 - accuracy: 0.9981 - val_loss: 3.4390 - val_accuracy: 0.6866
Epoch 479/500
27/27 [==============================] - 0s 2ms/step - loss: 1.6896e-04 - accuracy: 1.0000 - val_loss: 3.4254 - val_accuracy: 0.6866
Epoch 480/500
27/27 [==============================] - 0s 2ms/step - loss: 1.7642e-04 - accuracy: 1.0000 - val_loss: 3.4928 - val_accuracy: 0.6866
Epoch 481/500
27/27 [==============================] - 0s 2ms/step - loss: 1.0257e-04 - accuracy: 1.0000 - val_loss: 3.5151 - val_accuracy: 0.6866
Epoch 482/500
27/27 [==============================] - 0s 2ms/step - loss: 7.5138e-05 - accuracy: 1.0000 - val_loss: 3.5217 - val_accuracy: 0.6866
Epoch 483/500
27/27 [==============================] - 0s 2ms/step - loss: 6.3994e-04 - accuracy: 1.0000 - val_loss: 3.5667 - val_accuracy: 0.6866
Epoch 484/500
27/27 [==============================] - 0s 2ms/step - loss: 9.2943e-05 - accuracy: 1.0000 - val_loss: 3.5997 - val_accuracy: 0.6866
Epoch 485/500
27/27 [==============================] - 0s 2ms/step - loss: 9.6351e-04 - accuracy: 1.0000 - val_loss: 3.4459 - val_accuracy: 0.6716
Epoch 486/500
27/27 [==============================] - 0s 2ms/step - loss: 8.5210e-05 - accuracy: 1.0000 - val_loss: 3.3916 - val_accuracy: 0.6791
Epoch 487/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 3.6991 - val_accuracy: 0.7015
Epoch 488/500
27/27 [==============================] - 0s 2ms/step - loss: 1.5950e-04 - accuracy: 1.0000 - val_loss: 3.7574 - val_accuracy: 0.7015
Epoch 489/500
27/27 [==============================] - 0s 2ms/step - loss: 2.0122e-04 - accuracy: 1.0000 - val_loss: 3.7492 - val_accuracy: 0.6940
Epoch 490/500
27/27 [==============================] - 0s 2ms/step - loss: 1.9249e-04 - accuracy: 1.0000 - val_loss: 3.7707 - val_accuracy: 0.6940
Epoch 491/500
27/27 [==============================] - 0s 2ms/step - loss: 0.0011 - accuracy: 1.0000 - val_loss: 3.7897 - val_accuracy: 0.7015
Epoch 492/500
27/27 [==============================] - 0s 2ms/step - loss: 6.8487e-05 - accuracy: 1.0000 - val_loss: 3.8232 - val_accuracy: 0.7015
Epoch 493/500
27/27 [==============================] - 0s 2ms/step - loss: 9.7565e-04 - accuracy: 1.0000 - val_loss: 3.9159 - val_accuracy: 0.7090
Epoch 494/500
27/27 [==============================] - 0s 2ms/step - loss: 1.1929e-04 - accuracy: 1.0000 - val_loss: 4.0091 - val_accuracy: 0.7239
Epoch 495/500
27/27 [==============================] - 0s 2ms/step - loss: 1.6470e-04 - accuracy: 1.0000 - val_loss: 3.9735 - val_accuracy: 0.7164
Epoch 496/500
27/27 [==============================] - 0s 2ms/step - loss: 4.2354e-04 - accuracy: 1.0000 - val_loss: 3.9816 - val_accuracy: 0.7164
Epoch 497/500
27/27 [==============================] - 0s 2ms/step - loss: 2.0422e-04 - accuracy: 1.0000 - val_loss: 4.0228 - val_accuracy: 0.7164
Epoch 498/500
27/27 [==============================] - 0s 2ms/step - loss: 6.0921e-04 - accuracy: 1.0000 - val_loss: 4.0845 - val_accuracy: 0.7239
Epoch 499/500
27/27 [==============================] - 0s 2ms/step - loss: 1.1692e-04 - accuracy: 1.0000 - val_loss: 4.1211 - val_accuracy: 0.7313
Epoch 500/500
27/27 [==============================] - 0s 2ms/step - loss: 1.6110e-04 - accuracy: 1.0000 - val_loss: 4.1004 - val_accuracy: 0.7164

In [20]:
test_loss, test_acc = model.evaluate(X_test, y_test)

11/11 [==============================] - 0s 1ms/step - loss: 3.9857 - accuracy: 0.7515

In [21]:
def is_difficult_to_annotate(tweet:str) -> bool:
    answer = model.predict(embed([tweet]).numpy())
    return answer[0][0] < 0.5

In [24]:
is_difficult_to_annotate("RT @TeamCavuto: Protesters stage #DieIn protests in @Apple store in NYC... Is it me, or is this anger misplaced? RETWEET if you agree.")

False